version: 2
updates:

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    labels:
      - golang
      - dependencies
    groups:
      dependencies:
        patterns:
        - "*"

  - package-ecosystem: npm
    directory: /build/react-frontend/
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - npm
      - dependencies

    ignore:
    # Packages requiring ESM imports
    - dependency-name: 'camelcase'
      versions:
      - '>= 7'

    - dependency-name: 'react'
      versions:
        - '>= 19'
    - dependency-name: 'react-dom'
      versions:
        - '>= 19'
    - dependency-name: '@types/react'
      versions:
        - '>= 19'
    - dependency-name: '@types/react-dom'
      versions:
        - '>= 19'

    groups:
      dev-deps:
        dependency-type: development

  - package-ecosystem: docker
    directory: /build/package/
    schedule:
      interval: monthly
    labels:
      - dockerfile
      - dependencies
