version: 2
updates:

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - golang
      - dependencies

  - package-ecosystem: npm
    directory: /build/react-frontend/
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - npm
      - dependencies

    ignore:
    # Packages requiring ESM imports
    - dependency-name: 'camelcase'
      versions:
      - '>= 7'
    groups:
      dev-deps:
        dependency-type: development

  - package-ecosystem: docker
    directory: /build/package/
    schedule:
      interval: weekly
    labels:
      - dockerfile
      - dependencies
