{{- $fullName := include "helmrollbackweb.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helmrollbackweb.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.helmrollbackweb.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
