{{- $fullName := include "helmrollbackweb.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helmrollbackweb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.helmrollbackweb.secretenv }}
  {{ $key }} : {{ $value | b64enc | quote }}
  {{- end }}
