forto-app:
    app:
        secretenv:
            HELM_ROLLBACK_WEB_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:XmCm0PQUAC0OHgD6q0aWS5sdpjzUkNB8,iv:lg1W2krVFh7ogc671L3g/LIRB5YDZQfXbAMWQcZxGoc=,tag:r4oipgxGqkjeRLiFv1a2vw==,type:str]
            SLACK_APP_HELM_OAUTH_TOKEN: ENC[AES256_GCM,data:2mOESyHc33VT341x/MJkFAmV8Kkl6WCr68I+Xd43R7cw+Wq0bp5AZkVfiPiwY/2g19XWvfCOTw==,iv:pftW0sxY0GxXQLMdx6opJpfQ1PYZuM1vshvVPtTKvvc=,tag:bi41YzuekZmtzYpGNrqjGg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:389345400137:key/a2adf922-3133-4468-9a49-fd893617d98a
          created_at: "2020-05-25T11:43:23Z"
          enc: AQICAHg3cRPRxrwfxME6fhNBxH/aaizPzLvNKCoOxXkuUCEMUAGzuPuc7rAIS646KaCQjUH+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMuggtFb47dhxz8ipcAgEQgDuL+iAgQVookXYy4GNcGfWoI+CzUCb3mtG08l6jcsGjEVNVVUsy3YIn9BFazfUcNlN/H8zN+a+kJV+joA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gr78s9knue0dmjs8f0d8y60cw9aghetgwnpfrl65s5v2l0lr6fsquju6wa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdFF1OGtDSHBJcy84VUFU
            R0MxMDdodTdUTzFKQUM5NVkrV1RaQ3RobnpJClphRjFpbkc3RWQyTU9wSkFkU2Rs
            TkFrdXluSk4xN3dhbi9yeldGYWcwMXcKLS0tIERIVVdmSWY3eTQ5YnVQek5XMFZ1
            N3Y3aytvQ3MySU96azR5SnpuUUVqMVEKwqtsC4ApBEIsBd6PKgvwWTJMiS8rzRwN
            GBuxXG0iOOFLb1/G2TzmVT8YwNVLlrpZD/MPfXgPPl+90D4BAMYxcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T09:49:52Z"
    mac: ENC[AES256_GCM,data:IBl+eEdP158JQmFpLvo1PYul+/bXfGgKYU14pj5uO3+pX12t4wI5JsecdM21kJjpb5fkQB8y66jUNVu3SOgjxC0NdQr73xJlYlohmyT2rLITXp9mzk1Y5jlNqIdVAdOEAlwERSirPaqMnBvAfGrcF3gwXAoGdmTpbiREdD+lr90=,iv:wJPeJUjEuBLPg7iEa+U+TO7tc1jk/YBi/aEHT5CLcKg=,tag:88q9qq3uKBxqDQd5QZamXQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
