forto-app:
    app: null
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:389345400137:key/a2adf922-3133-4468-9a49-fd893617d98a
          created_at: "2020-05-25T11:43:23Z"
          enc: AQICAHg3cRPRxrwfxME6fhNBxH/aaizPzLvNKCoOxXkuUCEMUAEzdvNLMK7AJRaXW7JByhDuAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdd2uHe7isYOivCY1AgEQgDurcBIxm8o3QMIUgrYM0quCIlFsuYrrubmfdK5qg2lYrAZwA/BGFchRL4xgm3UjMtFh+9Qt/3+oXA2E1g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-26T11:28:01Z"
    mac: ENC[AES256_GCM,data:OjvDXCHj81yAaCBesEUZFKL20JqsKOah8ggzwwGEZPtjXbQ1F31q+Q5K4vXIsODtHmcZ3zmw/ZNTeor/DTusI1rB8MfBMXfQw08QNlwzD9AFA2zzFciP/zvLH/2N7uyyYq0kkLRS7GLQ4e1JOIMoK6gphmUeSWAeXCk2wzpy6VE=,iv:eNx/bcL8DkfMcNZr6Sg2tb3zpY6nEJJUr98CY0ShXeE=,tag:kSBi8ghWwUe9izu86WHZmg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
