forto-app:
    app:
        secretenv:
            HELM_ROLLBACK_WEB_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:SCDlUBJ3H4CYZgTVu1vX+A+5bBEwBYL8,iv:lg1W2krVFh7ogc671L3g/LIRB5YDZQfXbAMWQcZxGoc=,tag:bRkqCQ8e1jFCHy7lJOEufA==,type:str]
            SLACK_APP_HELM_OAUTH_TOKEN: ENC[AES256_GCM,data:qLoThV2JSAwkxNXDK7VU8NYVZyL289P5i+F9sb2cX6XNjk6lxmoySZiSbzxb2qKWEyXihwioCw==,iv:pftW0sxY0GxXQLMdx6opJpfQ1PYZuM1vshvVPtTKvvc=,tag:bMHosuSl1jDYPwPZE1VNVQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:389345400137:key/a2adf922-3133-4468-9a49-fd893617d98a
          created_at: "2020-05-25T11:43:23Z"
          enc: AQICAHg3cRPRxrwfxME6fhNBxH/aaizPzLvNKCoOxXkuUCEMUAEzdvNLMK7AJRaXW7JByhDuAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdd2uHe7isYOivCY1AgEQgDurcBIxm8o3QMIUgrYM0quCIlFsuYrrubmfdK5qg2lYrAZwA/BGFchRL4xgm3UjMtFh+9Qt/3+oXA2E1g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-26T15:19:30Z"
    mac: ENC[AES256_GCM,data:49+bjqDdvQd76j33T3gZk/i/yTPXRGgaVYf2SD33JwuDGQdAChwwkMIP+SsHL3EFfd/98Z87IS45dOdh25RtD5y307Ekx/ecGwIoCJR0pcaE4hlC3v8Gs75KfP6QGvhotptbEjit8K7JVzK4uVk2WKOto3vLj55eXqisgrjjc1g=,iv:gEXklpKggjXuN93EH0UghKuyXwzvf63XSun33BGnKbs=,tag:5CjQLIutsnQkzf+20gMRCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
