forto-app:
  nameOverride: helm-rollback-web
  forto:
    team: sre
    repository: https://github.com/freight-hub/helm-rollback-web
  image:
    repository: europe-west1-docker.pkg.dev/forto-artifacts/docker/helm-rollback-web
  app:
    env:
      HELM_ROLLBACK_WEB_OIDC_ISSUER: https://accounts.google.com
      HELM_ROLLBACK_WEB_OIDC_CLIENT_ID: 827794444486-s7n1oqbcscctg6r0g0j9ub1ut1etm576.apps.googleusercontent.com
      HELM_ROLLBACK_WEB_GOOGLE_GROUP_PASSLIST: terraformed-authz-engineers@forto.com,terraformed-authz-product-managers@forto.com,terraformed-authz-engineering-leads@forto.com
      HELM_ROLLBACK_WEB_HELM_COMMAND: /usr/bin/helm3
    deployments:
      api:
        replicaCount: 1
        containers:
        - probes:
            enabled: true
            probePathReadiness: "/"
            probePathLiveness: "/"
          preStopSleepDelay: 0
          cpuLimit: 1000m
          memLimit: 512Mi
          cpuRequest: 10m
          memRequest: 512Mi
          containerPort: 8080
        edgeStack:
          enabled: true
          prefix: /
  serviceAccount:
    create: true
    awsIdentity:
      enabled: false

#local Chart referencec
serviceAccount:
  create: true
