forto-app:
  datadog:
    environment: production
  app:
    env:
      HELM_ROLLBACK_WEB_CALLBACK_URL: https://helm-rollback.forto.com/callback-gl
      HELM_ROLLBACK_WEB_HOSTNAME: https://helm-rollback.forto.com
      HELM_ROLLBACK_WEB_NOTIFICATION_CHANNEL: "#sre-notifs"
      HELM_ROLLBACK_WEB_ENVIRONMENT: production
      HELM_ROLLBACK_WEB_THEME: red
    deployments:
      api:
        ingress:
          hosts:
          - host: helm-rollback.forto.com

#local Chart referencec
serviceAccount:
  create: true
  awsIdentity:
    enabled: false
