forto-app:
  app:
    env: {}
    deployments:
      api:
        replicaCount: 1
        ingress:
          hosts:
          - host: helm-rollback.forto.io
  serviceAccount:
    create: true
    annotations: {}
    name: null
  datadog:
    environment: sandbox
