forto-app:
  datadog:
    features:
      runtimeMetrics: false
      logInjection: false
  image:
    tag: dev
  app:
    env: 
      HELM_ROLLBACK_WEB_CALLBACK_URL: https://helm-rollback.forto.io/callback-gl
      HELM_ROLLBACK_WEB_HOSTNAME: https://helm-rollback.forto.io
      HELM_ROLLBACK_WEB_NOTIFICATION_CHANNEL: "#sre-notifs"
      HELM_ROLLBACK_WEB_ENVIRONMENT: sandbox
      HELM_ROLLBACK_WEB_THEME: blue
    deployments:
      api:
        replicaCount: 1
        ingress:
          hosts:
          - host: helm-rollback.forto.io
  serviceAccount: 
    awsIdentity:
      enabled: false

#local Chart referencec
serviceAccount:
  create: true
  awsIdentity:
    enabled: false