forto-app:
  nameOverride: helm-rollback-web
  image:
    repository: eu.gcr.io/freighthub-registry/helm-rollback-web
    tag: 0.0-linux-amd64
    pullPolicy: Always
  app:
    env: 
      HELM_ROLLBACK_WEB_OIDC_ISSUER: https://accounts.google.com
      HELM_ROLLBACK_WEB_OIDC_CLIENT_ID: 827794444486-s7n1oqbcscctg6r0g0j9ub1ut1etm576.apps.googleusercontent.com
      HELM_ROLLBACK_WEB_GOOGLE_GROUP_PASSLIST: terraformed-authz-engineers@forto.com,terraformed-authz-product-managers@forto.com
      HELM_ROLLBACK_WEB_HELM_COMMAND: /usr/bin/helm3
    deployments:
      api:
        replicaCount: 1
        containers:
        - cpuLimit: 1000m
          memLimit: 356Mi
          cpuRequest: 10m
          memRequest: 356Mi
        ingress:
          enabled: true
        service:
          enabled: true
        legacyExternalName: true
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: