forto-app:
  datadog:
    environment: sandbox
  app:
    env:
      HELM_ROLLBACK_WEB_CALLBACK_URL: https://helm-rollback.forto.io/callback-gl
      HELM_ROLLBACK_WEB_HOSTNAME: https://helm-rollback.forto.io
      HELM_ROLLBACK_WEB_NOTIFICATION_CHANNEL: "#sre-notifs"
      HELM_ROLLBACK_WEB_ENVIRONMENT: sandbox
      HELM_ROLLBACK_WEB_THEME: blue
    deployments:
      api:
        edgeStack:
          hosts:
            app:
              host: "helm-rollback.forto.io"
